name: A Modest Man
favicon: null
layout_spectrum: 0.21977851260453463
typography_spectrum: 0.0008709141984581947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.0015415623784065247
  saturation: 0.9266353466082364
  rhythmicContrast: 0.38655633688904345
purpose: []
